# Generated by Django 4.2.1 on 2023-06-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='company',
            field=models.CharField(default='Independent', max_length=100),
        ),
    ]
