# Generated by Django 4.2.1 on 2023-06-09 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0003_reporter_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.TextField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_service.reporter')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.ManyToManyField(to='blog_service.publisher'),
        ),
    ]
