# Generated by Django 4.2.1 on 2023-06-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_service', '0004_publisher_article_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='reporter',
        ),
    ]
